### ISSUE TITLE
?

### ISSUE THREAD

**Issue by jitterbug-perfume** [OfficialDarkzy/DRP-Framework#11]
https://github.com/OfficialDarkzy/DRP-Framework/blob/69bdf8a34cbcd1cb7e50c850e58498cc6148283c/3.%20Addons%20%5BCore%2C%20Community%5D/%5BDRPCOREADDONS%5D/drp_clothing/client.lua#L255

this line causes the resource to crash when switching colors

**Comment by OfficialDarkzy** [comment]
Because the opacity is not completed

**Comment by jitterbug-perfume** [comment]
Good reason!!!! Maybe just remove the line then.

**Comment by OfficialDarkzy** [comment]
The clothing is not 100% finished anyway. Calm down cock end. Dont see you making a framework :laughing:  just see you bitching about nothing

**Comment by low-cal** [comment]
Just pointing out a bug. Easy fix you could just remove. I will be releasing a framework within the next month... maybe by that time you'll have commented out this line ;)
