### ISSUE TITLE
Your not whitelisted

### ISSUE THREAD

**Issue by JessicaxD** [OfficialDarkzy/DRP-Framework#6]
After the last update, when i try to join its says your not whitelisted, but its not adding me to the db where i can set myself as whitelisted

**Comment by OfficialDarkzy** [comment]
Make sure your database is working correctly there will be an error in the console if it isnt working correctly.

**Comment by JessicaxD** [comment]
I got it now, i restarted my db :) now im getting this error when i try to login :) https://gyazo.com/53d62ca4d2544931c7167e7e8cf44f30

**Comment by OfficialDarkzy** [comment]
Dont worry about that error, that is an error because you didnt load into the server correctly or you crashed etc while loading in, i can fix that easily just not needed too yet.

**Comment by JessicaxD** [comment]
Ahh okei, i cant join cuz it crashes me when i try to join :)

**Comment by OfficialDarkzy** [comment]
restart your server cache

**Comment by JessicaxD** [comment]
https://gyazo.com/9d08098766dc76c936252c0313004818

**Comment by OfficialDarkzy** [comment]
Delete all the motels in motelrooms folder until motel_rooms7.ymap or just download the new update. 👍 please also use discord to post issues i dont always see it on here and its a pain to show stuff on here, use discord its easier

**Comment by JessicaxD** [comment]
Alright will do thanks! :)
