### ISSUE TITLE
face components

### ISSUE THREAD

**Issue by jitterbug-perfume** [OfficialDarkzy/DRP-Framework#9]
https://github.com/OfficialDarkzy/DRP-Framework/blob/69bdf8a34cbcd1cb7e50c850e58498cc6148283c/3.%20Addons%20%5BCore%2C%20Community%5D/%5BDRPCOREADDONS%5D/drp_clothing/client.lua#L239

Native does not call for ped in arguments

https://runtime.fivem.net/doc/natives/#_0xCF1CE768BB43480E

**Comment by OfficialDarkzy** [comment]
Incorrect. You can call ped because each ped is unique.

**Comment by jitterbug-perfume** [comment]
Reading skills 101:
GetNumHeadOverlayValues(overlayID --[[ integer ]])
The only argument is the overlayID smh

**Comment by jitterbug-perfume** [comment]
You really enjoy doubling down on basic mistakes don't you. Good coder!

**Comment by OfficialDarkzy** [comment]
I have not created this clothing menu from Scratch I have permission to use it on DRP. So you're not insulting me, cock end.

**Comment by OfficialDarkzy** [comment]
I did the backend and converted it from saving to txt to SQL. Dont see you doing that... :laughing:

**Comment by jitterbug-perfume** [comment]
Maybe the native changed since it was created by Frazzle, so I'm certain ly not insulting him. I'm laughing at you that you can't even read the native requirements today lol

**Comment by OfficialDarkzy** [comment]
haha its more work than that to work with the DatabaseAPI. Dont see you doing it tho do i? oh yeah no. I have no rush to do ANYTHING you ask me to do. Whats your framework going to be called? I am a lil bitch and have no care for anyone else because i am a spoilt 12 year old.

If you can do all this work then why are you here bitching? Fuck off and do a better job because I bet you cant. Fuck off. You. Nonce. :D

**Comment by jitterbug-perfume** [comment]
I have already fixed it but I don't like externalsql and therefore am rebuilding a framework using ghmattimysql. Have a nice day "nonce".

**Comment by OfficialDarkzy** [comment]
At least we can both relate to something! I don't like you :laughing:

**Comment by OfficialDarkzy** [comment]
Never met such a inconsiderate cunt in my life lol.

**Comment by jitterbug-perfume** [comment]
This is your professional github and you code for a living? Lol mate.

**Comment by OfficialDarkzy** [comment]
I dont code for a living. This isnt professional its my personal.

**Comment by jitterbug-perfume** [comment]
Are you sure about that mate? Pretty easy to find exactly where you work. Wonder if everyone there thinks you're a cunt too.

**Comment by OfficialDarkzy** [comment]
I am very sure lol! Is that a threat mate? Because I would advise you don't 😉 No no, everyone thinks you're a cunt lets get that right.

**Comment by jitterbug-perfume** [comment]
Just some friendly advice, when you're a cunt on the internet, at least don't link it to your exact name and business.

**Comment by OfficialDarkzy** [comment]
No no. You started being a cunt mate and I have no idea what you are on about LOL 😆

**Comment by jitterbug-perfume** [comment]
Right cause posting a bug on someone's github a MONTH ago makes me a cunt lmao. You're legit dense. Good luck picking out CSS color schemas for the rest of your life.

**Comment by OfficialDarkzy** [comment]
I am not even a web developer you fucking nonce! I am an Engineer in Fire & Security if that helps 💃

**Comment by OfficialDarkzy** [comment]
If i was a web developer id still be better than you bitching like a spastic because you didnt get your way 😆

**Comment by jitterbug-perfume** [comment]
Get my way fucking lol. This is your 'framework' I don't give a fuck if you fix the bugs anymore cause I've moved way past already. Cya nerd

**Comment by OfficialDarkzy** [comment]
Haha should of left alot earlier if you didnt care LOLOLOLOLOLOLOLOL fuck off retard.

**Comment by jitterbug-perfume** [comment]
You're funny to fuck with cause you think you're good at coding

**Comment by OfficialDarkzy** [comment]
At least im better than you 🗡

**Comment by jitterbug-perfume** [comment]
The fact that you think that is what makes it so funny. You can't even rip code to your own framework properly

**Comment by OfficialDarkzy** [comment]
go make ya framework m8 💃 wanna see all your code ill see ya in a month okay?

**Comment by OfficialDarkzy** [comment]
Jitter m8 go put some Purfume on you nonce, ya stinking over here with all this HHHHHHate. At least it is my code. 👍  Don't see any releases you have done either too scared to post it public?

**Comment by jitterbug-perfume** [comment]
My code is significantly more complete than yours. And considering the only thing you've done in the last month is make a vehicle auction system (fucking lol) I'm not too worried about what you think

**Comment by OfficialDarkzy** [comment]
ahaha because i've been working not sat at home playing FiveM because you're a nonce :D 

Come back when you've made a resource then you can bitch

**Comment by OfficialDarkzy** [comment]
and no RegisterCommand doesn't count

**Comment by jitterbug-perfume** [comment]
Plus be careful man. Everything you release still either says Xander, ISRP, Cadojrp, esx, etc. "my" code

**Comment by OfficialDarkzy** [comment]
ISRP/CADOJRP was the first section of the framework made by myself and Xander I have migrated it over because its mine. I was a dev on CADOJRP.

**Comment by OfficialDarkzy** [comment]
Anything I have permission to use and work around because ive asked, before you continue... You done yet? I can keep going on all day

**Comment by jitterbug-perfume** [comment]
Nah this is too funny tbh

**Comment by OfficialDarkzy** [comment]
Yeah man I am enjoying ripping you "tbh"

**Comment by OfficialDarkzy** [comment]
Ill be waiting for your framework okay 👯‍♂

**Comment by jitterbug-perfume** [comment]
Don't be too salty when you get it then mate

**Comment by jitterbug-perfume** [comment]
will be hard for you I know

**Comment by jitterbug-perfume** [comment]
maybe by then you'll have finished porting esx lockpicking to drp fucking LUL

**Comment by OfficialDarkzy** [comment]
Im really excited for it man! Gunna be REALLY epic I bet. Because you are clearly a WORLD CLASS developer yet you have not made a RESOURCE HAHAHAHAHAH

**Comment by OfficialDarkzy** [comment]
I published code im messing with its IN DEV BRANCH ASWELL AHHAHAHAHAHAHAHAHAHAH fucking virgin
